version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: patterns_nginx
    restart: always
    ports:
      - 127.0.0.1:7788:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - fpm
    networks:
      - patterns

  fpm:
    container_name: patterns
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - '9000:9000'
    restart: always
    environment:
      APP_ENV: dev
    volumes:
      - ./:/var/www/html
    networks:
      - patterns

networks:
  patterns:
    driver: bridge