Fundamentional:
  delegation: Delegation
  property_container: Property Container
  event_channel: Event Channel
Creational:
  simple_factory/bmw: Simple Factory
  static_factory/bmw: Static Factory
  factory_method/bmw: Factory Method
  abstract_factory/bmw: Abstract Method
  singleton: Singleton
  multiton: Multiton
  builder: Builder
  prototype: Prototype
  object_pull: Object Pull
Structural:
  adapter: Adapter
  facade: Facade
  bridge: Bridge
  composite: Composite
  decorator: Decorator
  proxy: Proxy
Behavioral:
  chain_of_responsibility: Chain of Responsibility
  strategy/easy: Strategy
  command: Command
  iterator: Iterator
  specification: Specification

SOLID:
  single_responsibility: Single responsibility
  open-closed: Open-closed
  liskov_substitution: Liskov substitution
  interface_segregation: Interface segregation
  dependency_inversion: Dependency Inversion
